version: '3.8'

services:
  backend:
    container_name: guess-backend
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:admin@db:5432/guess-db?schema=public
    command: ./wait-for-db.sh
    volumes:
      - .:/app

  db:
    container_name: guess-db
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: guess-that-nba-player
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: